// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-3DBQF0ElGlm_Gwfesi-snLW1trN328Y',
    appId: '1:909218036193:web:ea87fe43a75463c7713aa0',
    messagingSenderId: '909218036193',
    projectId: 'myprotfolio-57825',
    authDomain: 'myprotfolio-57825.firebaseapp.com',
    storageBucket: 'myprotfolio-57825.firebasestorage.app',
    measurementId: 'G-V78R583YHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4fxZn_qslmqw8WGVSGB4BYP5c2DQc2xQ',
    appId: '1:909218036193:android:d255807f622510c7713aa0',
    messagingSenderId: '909218036193',
    projectId: 'myprotfolio-57825',
    storageBucket: 'myprotfolio-57825.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn0Ff3xE3ah6ZqivdJSmv3s6M2IA7s-sc',
    appId: '1:909218036193:ios:d3a06aff5ddc6c68713aa0',
    messagingSenderId: '909218036193',
    projectId: 'myprotfolio-57825',
    storageBucket: 'myprotfolio-57825.firebasestorage.app',
    iosBundleId: 'com.example.myProtfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn0Ff3xE3ah6ZqivdJSmv3s6M2IA7s-sc',
    appId: '1:909218036193:ios:d3a06aff5ddc6c68713aa0',
    messagingSenderId: '909218036193',
    projectId: 'myprotfolio-57825',
    storageBucket: 'myprotfolio-57825.firebasestorage.app',
    iosBundleId: 'com.example.myProtfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-3DBQF0ElGlm_Gwfesi-snLW1trN328Y',
    appId: '1:909218036193:web:d9499381bb24037d713aa0',
    messagingSenderId: '909218036193',
    projectId: 'myprotfolio-57825',
    authDomain: 'myprotfolio-57825.firebaseapp.com',
    storageBucket: 'myprotfolio-57825.firebasestorage.app',
    measurementId: 'G-RKLHGRQB2N',
  );
}
